# Generated by Django 3.2.18 on 2023-04-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
